### PR TITLE
Update decode to new protocol

### PR DESCRIPTION
**Pull request by SpendBCH**

### CODE REVIEW

**Comment by cgcardona** [comment]
@GitCash 132031 satoshis for @SpendBCH

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/SpendBCH)
@SpendBCH

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/fyookball)
@fyookball

**Comment by cgcardona** [comment]
@GitCash 132031 satoshis for @gandrewstone

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/gandrewstone)
@gandrewstone

**Comment by cgcardona** [comment]
@GitCash 132031 satoshis for @zquestz

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/zquestz)
@zquestz

**Pull request merged**
